[package]
name = "rust-wfc"
version = "0.1.0"
authors = ["Chris McDonald <mail.chris.mcdonald@gmail.com>"]

[dependencies]
ndarray = "0.10.0"
rand = "0.3.15"
chrono = "0.3"
num-traits = "*"
image = "0.15.0"
bit-vec = "0.4.4"
itertools = "0.6"